logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://chatapp-messages:8081"
              - "http://chatapp-userchats:8082"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: chatapp_userchats
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:8082}
          predicates:
            - Path=/userchat/**

        - id: chatapp_auth
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:8082}
          predicates:
            - Path=/auth/**

        - id: chatapp_chat
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:8082}
          predicates:
            - Path=/chats/**
            
        - id: chatapp_messages
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:8081}
          predicates:
            - Path=/msg/**

        - id: chatapp_files
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:8081}
          predicates:
            - Path=/files/**

        - id: Media_Data
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_2_URI:http://localhost:8087}
          predicates:
            - Path=/media/**

        - id: temp_messages
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:8081}
          predicates:
            - Path=/temp/**
jwt:
  secret: ${JWT_SECRET:xfjlcyD4pLcXF011QjeJPyEKdnxxTSUq9AJ2AcqC0+o=}