logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://chatapp-messages:8081"
              - "http://chatapp-userchats:8082"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: chatapp_userchats
          uri: http://chatapp-userchats:8082
          predicates:
            - Path=/userchat/**

        - id: chatapp_auth
          uri: http://chatapp-userchats:8082
          predicates:
            - Path=/auth/**

        - id: chatapp_chat
          uri: http://chatapp-userchats:8082
          predicates:
            - Path=/chats/**
            
        - id: chatapp_test
          uri: http://chatapp-userchats:8082
          predicates:
            - Path=/new/**
            
        - id: chatapp_messages
          uri: http://chatapp-messages:8081
          predicates:
            - Path=/msg/**

jwt:
  secret: ${JWT_SECRET:xfjlcyD4pLcXF011QjeJPyEKdnxxTSUq9AJ2AcqC0+o=}